### ISSUE TITLE
Password toggle black in dark mode

### ISSUE THREAD

**Issue by MarkusThielker** [MarkusThielker/ory-kit#13]
## Description
![Screenshot of password input with black toggle icon](https://github.com/MarkusThielker/ory-template/assets/50532339/381d5cf7-72dd-4626-b1ac-b06064eb05d8)

**Comment by ChaudaryHammad** [comment]
could you please explain a bit more i want to solve it?

**Comment by MarkusThielker** [comment]
Hey, I'm currently not accepting code contributions to any of my GitHub projects. Thanks for your interest though.
Bug reports, feature requests, and other suggestions for improvement, on the other hand, are always welcome.
I see that the "good first issue" tag on the tickets was misleading, which is why I removed the tags.

**Comment by ChaudaryHammad** [comment]
ok buddy
